server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: spring

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
